# This workflow will publish
name: Python package publish

on:
  release:
    types: [published]
    branches:
      - release/py

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - name: Publish package distributions to PyPI
        run: |
          cd py
          pdm publish